### PR TITLE
Clean-up and fix Q-evolution notebook

### PR DESCRIPTION
**Pull request by p-zubieta**
There were additional issues with the Q-evolution notebook, we also fixed some remaining parts of the code for it to fully work in 2D.

@haeriamin

### CODE REVIEW

**Review by haeriamin — APPROVED** [review]
@pabloferz (and @j-salmeron), thanks for sharing. I was able to run the Q-evolution notebook and visualize the results in Paraview, however, I cannot verify them. If it is required (at this point) and there is a way that I can verify, please let me know. Otherwise, feel free to merge.

**Comment by j-salmeron** [comment]
Thanks for letting us know, Amin. Could you please let us know what you saw in Paraview? You can even make a movie. In principle, you should first see the decrease of the order parameter and then the formation of some +/- 1/2 defects everywhere that tend to attract and annihilate. If you do not see that, then try to make the time shorter or have more time steps, as the system might have reached equilibrium very fast (at equilibrium the order parameter should be homogeneous and around 0.3). If nothing works, please let us know to see what the problem might be.

**Comment by j-salmeron** [comment]
Once, you see that, I think maybe an interesting next step for you might be to help us writing a notebook where both equations are solved simultaneously:)

**Comment by Noe-Atzin** [comment]
Maybe we can have a folder in Box or Dropbox and see the Paraview files or
share the movies and have a better idea.

Sometimes with the move we can see if something is not working.

**Comment by haeriamin** [comment]
Thanks guys for letting me know. Here you can see a video of the simulation showing the scalar S field in the background and the vector n field (vector colors represent the value of n in the x-direction) -- please download it for the original quality.

https://www.dropbox.com/s/8jj6zxfjcuyn75q/S%26n.avi?dl=0

Btw, I have created a Dropbox shared folder in case we want to share our large files.

**Comment by haeriamin** [comment]
> Once, you see that, I think maybe an interesting next step for you might be to help us writing a notebook where both equations are solved simultaneously:)

Yeah, it is interesting; I will try to implement it (probably by sort of combining the already implemented Q and Phi equations).

**Comment by j-salmeron** [comment]
Thanks Amin for sharing. 
Just a couple of things. S in a nematic Liquid Crystal with a constant U of 3.5 should not be higher than 0.6. So you can make its color map range from 0 to 0.6 (not 1). In addition, the director vector should be drawn with a line (and not an arrow) as the head and the tail are indistinguishable in this theory. You need not use the magnitude in any direction of the director vector, instead just use a solid color, you can also play with the size of the line. I am suspicious about the results so I will check it myself. But, you can work on that.

**Comment by j-salmeron** [comment]
@haeriamin  to create a notebook solving both equations simultaneously, you can check the reaction-diffusion notebook, where 3 equations are being solved simultaneously. You can also take inspiration form my old Python code.

**Comment by p-zubieta** [comment]
@haeriamin We finally found the issue, it was just that we were missing writing a zero for the third dimension in the vtk vector field for the 2D case. Would you be able to run things again just to see if this matches the other notebook provided by @j-salmeron?

**Pull request merged**
